### ISSUE TITLE
Audio is mono only when using companion to play

### ISSUE THREAD

**Issue by micahchristensen** [bitfocus/companion-module-haivision-connectdvr#12]
I have been using the functions in companion to skip forward/backward, Play/pause and set cue points but have been finding that the audio will only play back on the left, the issues do not occur when triggering the same actions via Hai Visions web GUI, is anyone els finding the same issues?
Much appreciated!

**Comment by onfire4g05** [comment]
Are you using the latest version of Companion? The latest beta build?

Are you using an HLS stream and how many audio channels?

Finally, what version of the connect DVR are you running?

**Comment by micahchristensen** [comment]
I am running an older beta build (2.2.0-af44801d-3507) of companion 

Sorry i am not too savey on what HLS is but i would assume yes from looking at a couple things on the Hai Vision Connect website, and we run 8 audio channels 

DVR connect version is 4.7.0 build 52

In digging a little further today, i have found that it it is NOT the Play/Pause triggers that are causing it but rather when i recall a cue point is when it happens, also it looks like it only plays the audio from channel 1 and not the rest.

Thanks

**Comment by micahchristensen** [comment]
Massive apologies, i hadn't checked/realised  that there was a stable and released version of companion 2.2.0, the issue seam to have been found and fixed with that release
