### ISSUE TITLE
Error on Windows builds

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion-module-haivision-connectdvr#3]
Building companion v2.0.0 (2.0.0-5ceee140-2244) for windows, when it runs, I get this error in the warnings log.

**module(haivision-connectdvr): Error loading module: Error: 'darwin-x64' binaries cannot be used on the 'win32-x64' platform. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.**

**Comment by onfire4g05** [comment]
Sharp vendor code has been removed from this module; this sounds like something hasn't been cleaned and/or updated before trying to run.

**Comment by MeestorX** [comment]
Was it removed recently?

**Comment by onfire4g05** [comment]
Yes, see #2.
